# Setup
title:               'Alessandro Carraro'
#tagline:             'A blog about my thoughts and experiences.'
description:         'Welcome to my blog. Here I will share my projects'
url:                 'https://alecarraro.github.io'
#baseurl:             '/alecarraro-blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alessandro Carraro
  url:
  #email:             your-email@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
