# Setup
title:               My Blog
tagline:             'A blog about my thoughts and experiences.'
description:         'Welcome to my blog. Here I will share my thoughts on various topics.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Your Name
  url:
  email:             your-email@example.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
